### PR TITLE
New branch

### PR DESCRIPTION
**Pull request by GitArya27**
This is The UI for the other two pages .
this should solve the issue #2  , as for the slight difference in the figma and this UI design is because of and backend process is still pending .
I hope this get merged .

Areas
parking slot

### CODE REVIEW

**Comment by GitArya27** [comment]
this solves issue #2

**Comment by brahma-keerthi** [comment]
Hey @GitArya27 , we really appreciate your work. But the Number of slots available in AdminMainActivity should display the slots that as in UserMainActivity. So it would be better if this is solved as shown in readme.

**Comment by brahma-keerthi** [comment]
Also in the UserMainActivity, only 7 slots are seen. But number of free slots and number of occupied slots adds up to 12.
So we suggest u to work on this also.
But so far u have done a phenomenal work :)

**Comment by GitArya27** [comment]
Recycler view is used to display data taken from admin. So number of slots is dynamic and can be incresed by simply adding data from AdminMain. As for to display in UserMain same goes for it , as recycler view is used for the same.

Making changes on recycler will be covered in another issue i.e. connection with firebase, for which i will send a seperate pr, but for now it will solve issue #2 . So if u think it is good enough please merge it. Thank U

**Comment by brahma-keerthi** [comment]
Hey @GitArya27 , 
         Yes, number of slots is dynamic. But in real time the slots displayed in UserMainActivity must be same as AdminMainActivity. This is because the Admin updates to firebase and user retrieves it from firebase. But in ur commit, the AdminMainActivity does not display any slots. But in UserMainActivity there are slots.... This looks inappropriate. So, we would suggest you to look into this again.

Keep Trying....
All the best.

**Comment by brahma-keerthi** [comment]
Great work @GitArya27 !!!
Can u add some newer areas and display the slots?.... Coz we need to review ur pr

**Comment by brahma-keerthi** [comment]
Also in the UserMainActivity, we see only 2 green slots. But the number of free slots displayed is 7. So we recommend to solve this..

**Comment by GitArya27** [comment]
These are few changes as requested 
-> the number of green slots and red slots will be displayed accordingly 
-> Added newer Areas and Displayed 



A2
A1

**Comment by brahma-keerthi** [comment]
Hey @GitArya27 ,  in area R, we see only 4 slots. But UI tells it as 12. Its inappropriate. So we suggest to look into this matter

**Comment by GitArya27** [comment]
Total Number of spots now updated

**Comment by brahma-keerthi** [comment]
Congratulations @GitArya27 on your 2nd contribution. 
We are looking forward to your valuable contributions to other issues as well !!!

HappyCoding :)

**Pull request merged**
